### ISSUE TITLE
"explanation" is misspelled in _review.md

### ISSUE THREAD

**Issue by odidev** [zachlas/arm-software-developers-ads#18]
In **_review.md** file of all modules in "**/content/learning-paths/**" directory , word "explanation" is misspelled as "explination" and if i am correcting the same, explanation of question doesn't get displayed when running hugo server locally. This needs to be corrected.

**Comment by jasonrandrews** [comment]
Thanks for reporting this, it has been fixed. All of the Learning Paths have the correct spelling and the display code has been fixed to match.
